version: '3.8'

services:
  web-locationproject:
    build:
      context: .
    container_name: locationproject_container
    ports:
      - "8082:8082"
    environment:
      APP_HOME: /com/example/locationproject
    volumes:
      - ./build/libs:/com/example/locationproject/libs
    command: ["java", "-jar", "locationProject-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - postgres-locationproject


  postgres-locationproject:
    container_name: postgres-locationproject
    image: postgres:15-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file:
      - .postgre_env


  nginx:
    restart: always
    depends_on:
      - web-locationproject
    volumes:
      - ./build/libs:/com/example/locationproject/libs
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"